# Archivo de changelog (ajusta la ruta según tu estructura)
changeLogFile=/db/changelog/db.changelog-master.yaml

# Configuración de conexión a PostgreSQL
url=jdbc:postgresql://db:5432/ecommerce_db
username=admin
password=admin123
driver=org.postgresql.Driver

# Opciones adicionales recomendadas
liquibase.command.validate=true
logLevel=INFO